# PHP + Apache の公式イメージを使用
FROM php:8.2-apache
RUN php -v
# パッケージリストを更新し、必要なシステムパッケージをインストール
RUN apt-get update && apt-get install -y \
    unzip \
    curl \
    libxml2-dev \
    libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

# 必要な PHP 拡張モジュールをインストール
RUN docker-php-ext-install mbstring xml curl

# Python 環境を統一
RUN ln -s /usr/bin/python3 /usr/bin/python

# 日本語環境を設定
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ Asia/Tokyo
ENV TERM xterm

# 作業ディレクトリ
WORKDIR /bot

# pip install
COPY requirements.txt /bot/
RUN pip install -r requirements.txt

# composer install
RUN apt-get install -y curl unzip && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install

# コードをコピー
COPY . /bot

# ポート開放
EXPOSE 8080

CMD ["python3", "/bot/main.py"]
